service: workspaces-services

useDotenv: true

plugins:
  - serverless-webpack
  - serverless-webpack-prisma
  - serverless-offline
  - serverless-domain-manager

custom:
  customDomain:
    domainName: workspaces.services.grida.co
    certificateName: "*.workspaces.services.grida.co"
    hostedZoneId: us-west-1
    basePath: ""
    stage: production
    createRoute53Record: true
  serverless-offline:
    httpPort: 4401
    noPrependStageInUrl: true
  webpack:
    includeModules: true

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
    DATABASE_URL: ${env:DATABASE_URL}
    COOKIE_ACCESS_TOKEN_KEY: ${env:COOKIE_ACCESS_TOKEN_KEY}

package:
  individually: true

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: GET
          path: /
      - http:
          method: any
          path: /{proxy+}
